# AGLint config file
# Documentation: https://github.com/AdguardTeam/AGLint#configuration

root: true
allowInlineConfig: true
extends:
  - aglint:recommended
syntax:
  - AdblockPlus
  - AdGuard
  - UblockOrigin
